# Colors
set-option -a terminal-features 'xterm-256color:RGB'
set -g default-terminal "xterm-256color" 
set -g status-bg "#da6201" 
set -g status-fg "#ffcb83"

# Reduce delay when pressing prefix key
set -g set-clipboard on
set-option -sg escape-time 10

# Vim-nav
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use vim keybindings in copy mode
set-window-option -g mode-keys vi 
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection
bind-key -T copy-mode-vi C-v send -X rectangle-toggle

# The one time I want 1-based indexing
set -g base-index 1
setw -g pane-base-index 1
