#!/bin/bash

# Globals
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. $SCRIPT_DIR/.env >/dev/null 2>&1 || { >&2 echo "Missing environment file!"; exit 1; }

# Helpers 
link_bak () { # Link with backup ($1: Target, $2: Replacement)
    # Remove old backup
	if [[ -L $1.bak || -f $1.bak || -d $1.bak ]]; then
        rm -rf $1.bak
    fi

	if [[ -L $1 || -f $1 ||  -d $1 ]]; then
		sudo mv -f $1 $1.bak
	fi

	echo " > Linking $SCRIPT_DIR/$2 -> $1"
	ln -s $SCRIPT_DIR/$2 $1
}

bak () { # Move file to backup ($1: Target)
    # Remove old backup
	if [[ -L $1.bak || -f $1.bak || -d $1.bak ]]; then
        rm -rf $1.bak
    fi

	if [[ -L $1 || -f $1 || -d $1 ]]; then
		sudo mv -f $1 $1.bak
	fi
}

# Actions
## Install APT Packages
install_packages () {
	if [ -f /etc/debian_version ]; then
        sudo apt -o Apt::Cmd::Disable-Script-Warning=true update -y
        sudo apt -o Apt::Cmd::Disable-Script-Warning=true install -y $(cat $SCRIPT_DIR/packages.txt)
    elif [ -f /etc/fedora-release ] || [ -f /etc/redhat-release ]; then
        sudo dnf update -y
        sudo dnf install -y $(cat $SCRIPT_DIR/packages.txt)
    else
    	>&2 echo "Package manager expects a Debian/Fedora-based distribution!"
		>&2 echo "Install the packages from ${SCRIPT_DIR}/packages.txt using your package manager."
		exit 1
	fi
}

## Install Neovim
install_nvim () {
	curl -LO https://github.com/neovim/neovim/releases/download/$NEOVIM_VERSION/$NEOVIM_PKG.tar.gz
	bak /opt/$NEOVIM_PKG
	sudo tar -C /opt -xzf $NEOVIM_PKG.tar.gz
	sudo rm -f $NEOVIM_PKG.tar.gz
	bak /usr/bin/nvim
    bak /usr/bin/vim
	bak /usr/bin/vi
	sudo ln -s /opt/$NEOVIM_PKG/bin/nvim /usr/bin/vim
	sudo ln -s /opt/$NEOVIM_PKG/bin/nvim /usr/bin/nvim
	sudo ln -s /opt/$NEOVIM_PKG/bin/nvim /usr/bin/vi
}

## Install Node and Required Packages
install_node () {
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm install $NODE_VERSION || { echo "Couldn't install Node.JS!"; exit 1; }
    nvm use $NODE_VERSION
    npm install -g pyright
}

## Install LazyGit
install_lazygit () {
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    sudo install lazygit -D -t /usr/local/bin/
    rm -rf lazygit.tar.gz lazygit
}

## Install VSCode
install_vscode () {
    if [ -f /etc/debian_version ]; then
        sudo apt-get update
        sudo apt-get install -y wget gpg
        wget -O- https://packages.microsoft.com/keys/microsoft.asc \
          | gpg --dearmor \
          | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main" \
          | sudo tee /etc/apt/sources.list.d/vscode.list
        sudo apt-get update
        sudo apt-get install -y code
    elif [ -f /etc/fedora-release ] || [ -f /etc/redhat-release ]; then
        sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
        sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
        sudo dnf check-update || true
        sudo dnf install -y code
    else
        >&2 echo "VSCode installer requires a Debian/Fedora-based distribution!"
        exit 1
    fi

    cat "${SCRIPT_DIR}/.config/Code/extensions.txt" | xargs -n 2 code --install-extension
}

## Link Configurations in Home
install_configs () {
    configs=(
        .tmux.conf
        .bashrc
        .config/nvim
        .config/tabby
        .config/Code/User/settings.json
        .config/Code/User/keybindings.json
    )

    for i in "${configs[@]}"; do
        link_bak ~/$i $i
    done
}

## Configure fonts
configure_fonts () {
    sudo cp "${SCRIPT_DIR}/.local/share/fonts/*" /usr/local/share/fonts
    fc-cache -fv
}

## System Configurations
config_system () {
    echo "setxkbmap -option caps:none" >> ~/.profile # No caps
    gsettings set org.gnome.desktop.input-sources xkb-options "['caps:none']"
}

cat <<EOF
┳┳┓    ╹   ┓ •        ┏┓    ┏•             
┃┃┃┏┓╋╋ ┏  ┃ ┓┏┓┓┏┓┏  ┃ ┏┓┏┓╋┓┏┓┓┏┏┓┏┓╋┏┓┏┓
┛ ┗┗┻┗┗ ┛  ┗┛┗┛┗┗┻┛┗  ┗┛┗┛┛┗┛┗┗┫┗┻┛ ┗┻┗┗┛┛ 
EOF

while true; do
    cat <<EOF
This script needs to be run after a fresh system install.
File's may be manually used and added if the install isn't
fresh, or in order to apply patches.
EOF

    read -p "Do you want to proceed? (y/n) " yn
    case $yn in
        [Yy]* ) 
            break;;
        [Nn]* ) 
            echo "Exiting..."
            exit;;
        * ) 
            echo "Invalid response. Please answer y or n.";;
    esac
done

install_packages &&
install_nvim &&
install_configs &&
configure_fonts &&
install_vscode &&
install_node &&
install_lazygit &&
config_system
